### ISSUE TITLE
Failed opening required 'include/stringstreamwrapper.php

### ISSUE THREAD

**Issue by Yzord** [b1gMail/zpush-b1gmail#2]
I'm trying to install Z-push on my server with the latest release, but when I installed it like your Install file told me (watch out, this also needs to be done in /usr/share/z-push/autodiscover/config.php) I get the following meesage in my error log:

> [Mon Jan 04 22:01:51.211675 2016] [:error] [pid 11087] [client 94.102.50.73:52448] PHP Fatal error: >require_once(): Failed opening required 'include/stringstreamwrapper.php' (include_path='.:/usr/share/pear:/usr/share/php') in /usr/share/z-push/backend/b1gmail/b1gmail.php on line 31 

And indeed, the latest version does not have this file anymore. I don't have enough knowledge to fix this, so i hope you can point me to the right direction?

**Comment by Yzord** [comment]
Deleted that line from b1gmail.php and the link is working, but it cannot authorize my user:

04/01/2016 22:10:31 [11249] [INFO] [unknown] Version='2.2.7' method='GET' from='94.xx.50.73' cmd='' getUser='unknown' devId='' devType=''
04/01/2016 22:10:31 [11249] [WARN] [unknown] /usr/share/z-push/backend/b1gmail/b1gmail.php:31 require_once(include/stringstreamwrapper.php): failed to open stream: No such file or directory (2)
04/01/2016 22:11:40 [11090] [INFO] [unknown] Version='2.2.7' method='GET' from='94.xx.50.73' cmd='' getUser='unknown' devId='' devType=''
04/01/2016 22:11:40 [11090] [INFO] [unknown] FileStateMachine->SetStateVersion() saving supported state version, value '2'
04/01/2016 22:11:40 [11090] [INFO] [unknown] AuthenticationRequiredException: Access denied. Please send authorisation information - code: 0
04/01/2016 22:11:40 [11090] [INFO] [unknown] User-agent: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10.10; rv:43.0) Gecko/20100101 Firefox/43.0'
04/01/2016 22:12:00 [11087] [INFO] [test] Version='2.2.7' method='GET' from='94.xx.50.73' cmd='' getUser='test' devId='' devType=''
04/01/2016 22:12:00 [11087] [ERROR] [test] Login as "test" failed: user not found
04/01/2016 22:12:00 [11087] [INFO] [test] AuthenticationRequiredException: Access denied. Username or password incorrect - code: 0

Synchronization is ON for that account.

**Comment by pschlan** [comment]
Hi,

you cannot simply delete the line, it will break a lot of things. Please use a compatible Z-Push version (2.1 branch) until I've updated the connector to work with the current version.

**Comment by Yzord** [comment]
Ah ok, let me try that.

EDIT: 2.1.3 is working ok

**Comment by pschlan** [comment]
Hi again,

I've created a new branch "zpush-22" (https://github.com/b1gMail/zpush-b1gmail/tree/zpush-22) with a version which I've slightly customized for Z-Push 2.2. Please also read the updated INSTALL file about a new configuration setting USE_FULLEMAIL_FOR_LOGIN.

Can you try with that version and verify if this problem is fixed now?
